package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdFormapago generated by hbm2java
 */
@Entity
@Table(name = "dd_formapago", catalog = "jbossforge")
public class DdFormapago implements java.io.Serializable {

	private static final long serialVersionUID = -27911572808417628L;
	private int idformapago;
	private String nombre;

	public DdFormapago() {
	}

	public DdFormapago(String nombre) {
		this.nombre = nombre;
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idformapago", unique = true, nullable = false)
	public int getIdformapago() {
		return this.idformapago;
	}

	public void setIdformapago(int idformapago) {
		this.idformapago = idformapago;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
