package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdFormapago generated by hbm2java
 */
@Entity
@Table(name = "dd_formapago", catalog = "jbossforge")
@XmlRootElement
public class DdFormapago implements java.io.Serializable {

	private static final long serialVersionUID = 4312637913157211011L;
	private int idformapago;
	private String nombre;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public DdFormapago() {
	}

	public DdFormapago(int idformapago) {
		this.idformapago = idformapago;
	}
	public DdFormapago(int idformapago, String nombre, Set<Entrada> entradas) {
		this.idformapago = idformapago;
		this.nombre = nombre;
		this.entradas = entradas;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO) 
	@Column(name = "idformapago", unique = true, nullable = false)
	public int getIdformapago() {
		return this.idformapago;
	}

	public void setIdformapago(int idformapago) {
		this.idformapago = idformapago;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddFormapago")
	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
