package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdOrigenEntrada generated by hbm2java
 */
@Entity
@Table(name = "dd_origen_entrada", catalog = "jbossforge")
@XmlRootElement
public class DdOrigenEntrada implements java.io.Serializable {

	private static final long serialVersionUID = -7320896745270200719L;
	private int idorigenEntrada;
	private String nombre;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public DdOrigenEntrada() {
	}

	public DdOrigenEntrada(int idorigenEntrada, String nombre) {
		this.idorigenEntrada = idorigenEntrada;
		this.nombre = nombre;
	}
	public DdOrigenEntrada(int idorigenEntrada, String nombre,
			Set<Entrada> entradas) {
		this.idorigenEntrada = idorigenEntrada;
		this.nombre = nombre;
		this.entradas = entradas;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO) 
	@Column(name = "idorigen_entrada", unique = true, nullable = false)
	public int getIdorigenEntrada() {
		return this.idorigenEntrada;
	}

	public void setIdorigenEntrada(int idorigenEntrada) {
		this.idorigenEntrada = idorigenEntrada;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddOrigenEntrada")
	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
