package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DdPatrocinadorEventoId generated by hbm2java
 */
@Embeddable
public class DdPatrocinadorEventoId  implements java.io.Serializable {

	private static final long serialVersionUID = 8873218804088621893L;
	private int idpatrocinador;
     private int idevento;

    public DdPatrocinadorEventoId() {
    }

    public DdPatrocinadorEventoId(int idpatrocinador, int idevento) {
       this.idpatrocinador = idpatrocinador;
       this.idevento = idevento;
    }
   


    @Column(name="idpatrocinador", nullable=false)
    public int getIdpatrocinador() {
        return this.idpatrocinador;
    }
    
    public void setIdpatrocinador(int idpatrocinador) {
        this.idpatrocinador = idpatrocinador;
    }


    @Column(name="idevento", nullable=false)
    public int getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(int idevento) {
        this.idevento = idevento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DdPatrocinadorEventoId) ) return false;
		 DdPatrocinadorEventoId castOther = ( DdPatrocinadorEventoId ) other; 
         
		 return (this.getIdpatrocinador()==castOther.getIdpatrocinador())
 && (this.getIdevento()==castOther.getIdevento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdpatrocinador();
         result = 37 * result + this.getIdevento();
         return result;
   }   


}


