package org.dinamizadores.dinaeventos.model;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DdRrppJefeEntrada generated by hbm2java
 */
@Entity
@Table(name="dd_rrpp_jefe_entrada", catalog="jbossforge")
public class DdRrppJefeEntrada  implements java.io.Serializable {

	private static final long serialVersionUID = -332369320880420937L;
	private DdRrppJefeEntradaId id;
    private Entrada entrada;
    private RrppJefes rrppJefes;
    private RrppMinion rrppMinion;

    public DdRrppJefeEntrada() {
    }

	
    public DdRrppJefeEntrada(DdRrppJefeEntradaId id, Entrada entrada, RrppJefes rrppJefes) {
        this.id = id;
        this.entrada = entrada;
        this.rrppJefes = rrppJefes;
    }
    public DdRrppJefeEntrada(DdRrppJefeEntradaId id, Entrada entrada, RrppJefes rrppJefes, RrppMinion rrppMinion) {
       this.id = id;
       this.entrada = entrada;
       this.rrppJefes = rrppJefes;
       this.rrppMinion = rrppMinion;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idRrppJefe", column=@Column(name="id_rrpp_jefe", nullable=false) ), 
        @AttributeOverride(name="idEntrada", column=@Column(name="id_entrada", nullable=false) ) } )
    public DdRrppJefeEntradaId getId() {
        return this.id;
    }
    
    public void setId(DdRrppJefeEntradaId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entrada", nullable=false, insertable=false, updatable=false)
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rrpp_jefe", nullable=false, insertable=false, updatable=false)
    public RrppJefes getRrppJefes() {
        return this.rrppJefes;
    }
    
    public void setRrppJefes(RrppJefes rrppJefes) {
        this.rrppJefes = rrppJefes;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rrpp_minion")
    public RrppMinion getRrppMinion() {
        return this.rrppMinion;
    }
    
    public void setRrppMinion(RrppMinion rrppMinion) {
        this.rrppMinion = rrppMinion;
    }
}


