package org.dinamizadores.dinaeventos.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DdRrppJefeEntradaId generated by hbm2java
 */
@Embeddable
public class DdRrppJefeEntradaId  implements java.io.Serializable {

	private static final long serialVersionUID = 4459539644440674000L;
	private int idRrppJefe;
    private int idEntrada;

    public DdRrppJefeEntradaId() {
    }

    public DdRrppJefeEntradaId(int idRrppJefe, int idEntrada) {
       this.idRrppJefe = idRrppJefe;
       this.idEntrada = idEntrada;
    }

    @Column(name="id_rrpp_jefe", nullable=false)
    public int getIdRrppJefe() {
        return this.idRrppJefe;
    }
    
    public void setIdRrppJefe(int idRrppJefe) {
        this.idRrppJefe = idRrppJefe;
    }


    @Column(name="id_entrada", nullable=false)
    public int getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(int idEntrada) {
        this.idEntrada = idEntrada;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DdRrppJefeEntradaId) ) return false;
		 DdRrppJefeEntradaId castOther = ( DdRrppJefeEntradaId ) other; 
         
		 return (this.getIdRrppJefe()==castOther.getIdRrppJefe())
 && (this.getIdEntrada()==castOther.getIdEntrada());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRrppJefe();
         result = 37 * result + this.getIdEntrada();
         return result;
   }   

}


