package org.dinamizadores.dinaeventos.model;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DdRrppJefeEntrada generated by hbm2java
 */
@Entity
@Table(name="dd_rrpp_jefe_entrada", catalog="jbossforge")
public class DdRrppJefeEntrada  implements java.io.Serializable {

	private static final long serialVersionUID = 1044531646797285709L;
	private Integer idRrppJefeEntrada;
    private Entrada entrada;
    private RrppJefes rrppJefes;
    private RrppMinion rrppMinion;

   public DdRrppJefeEntrada() {
   }

	
   public DdRrppJefeEntrada(Entrada entrada, RrppJefes rrppJefes) {
       this.entrada = entrada;
       this.rrppJefes = rrppJefes;
   }
   public DdRrppJefeEntrada(Entrada entrada, RrppJefes rrppJefes, RrppMinion rrppMinion) {
      this.entrada = entrada;
      this.rrppJefes = rrppJefes;
      this.rrppMinion = rrppMinion;
   }
  
   @Id @GeneratedValue(strategy=IDENTITY)
   @Column(name="id_rrpp_jefe_entrada", unique=true, nullable=false)
   public Integer getIdRrppJefeEntrada() {
       return this.idRrppJefeEntrada;
   }
   
   public void setIdRrppJefeEntrada(Integer idRrppJefeEntrada) {
       this.idRrppJefeEntrada = idRrppJefeEntrada;
   }

   @ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="id_entrada", nullable=false)
   public Entrada getEntrada() {
       return this.entrada;
   }
   
   public void setEntrada(Entrada entrada) {
       this.entrada = entrada;
   }

   @ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="id_rrpp_jefe", nullable=false)
   public RrppJefes getRrppJefes() {
       return this.rrppJefes;
   }
   
   public void setRrppJefes(RrppJefes rrppJefes) {
       this.rrppJefes = rrppJefes;
   }

   @ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="id_rrpp_minion")
   public RrppMinion getRrppMinion() {
       return this.rrppMinion;
   }
   
   public void setRrppMinion(RrppMinion rrppMinion) {
       this.rrppMinion = rrppMinion;
   }
}


