package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DdRrppEvento generated by hbm2java
 */
@Entity
@Table(name = "dd_rrpp_evento", catalog = "jbossforge")
public class DdRrppEvento implements java.io.Serializable {

	private static final long serialVersionUID = -5385338543978897202L;
	private DdRrppEventoId id;

	public DdRrppEvento() {
	}

	public DdRrppEvento(DdRrppEventoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idevento", column = @Column(name = "idevento", nullable = false)),
			@AttributeOverride(name = "idrrpp", column = @Column(name = "idrrpp", nullable = false))})
	public DdRrppEventoId getId() {
		return this.id;
	}

	public void setId(DdRrppEventoId id) {
		this.id = id;
	}

}
