package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdSexo generated by hbm2java
 */
@Entity
@Table(name = "dd_sexo", catalog = "jbossforge")
@XmlRootElement
public class DdSexo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1496682806215900571L;
	private int idsexo;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public DdSexo() {
	}

	public DdSexo(int idsexo, String nombre) {
		this.idsexo = idsexo;
		this.nombre = nombre;
	}
	public DdSexo(int idsexo, String nombre, Set<Usuario> usuarios) {
		this.idsexo = idsexo;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idsexo", unique = true, nullable = false)
	public int getIdsexo() {
		return this.idsexo;
	}

	public void setIdsexo(int idsexo) {
		this.idsexo = idsexo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddSexo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
