package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdSexo generated by hbm2java
 */
@Entity
@Table(name = "dd_sexo", catalog = "jbossforge")
public class DdSexo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4645018203711177069L;
	private int idsexo;
	private String nombre;

	public DdSexo() {
	}

	public DdSexo(int idsexo, String nombre) {
		this.idsexo = idsexo;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idsexo", unique = true, nullable = false)
	public int getIdsexo() {
		return this.idsexo;
	}

	public void setIdsexo(int idsexo) {
		this.idsexo = idsexo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
