package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdTipoEvento generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_evento", catalog = "jbossforge")
@XmlRootElement
public class DdTipoEvento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7158322830248428572L;
	private int idTipoEvento;
	private String tipoEvento;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public DdTipoEvento() {
	}

	public DdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}
	public DdTipoEvento(int idTipoEvento, String tipoEvento, Set<Evento> eventos) {
		this.idTipoEvento = idTipoEvento;
		this.tipoEvento = tipoEvento;
		this.eventos = eventos;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_tipo_evento", unique = true, nullable = false)
	public int getIdTipoEvento() {
		return this.idTipoEvento;
	}

	public void setIdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	@Column(name = "tipo_evento", length = 45)
	public String getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(String tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddTipoEvento")
	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
