package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdTiposIva generated by hbm2java
 */
@Entity
@Table(name = "dd_tipos_iva", catalog = "jbossforge")
@XmlRootElement
public class DdTiposIva implements java.io.Serializable {

	private static final long serialVersionUID = 4675200136023075100L;
	private int idtipoiva;
	private String nombre;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public DdTiposIva() {
	}

	public DdTiposIva(int idtipoiva) {
		this.idtipoiva = idtipoiva;
	}
	public DdTiposIva(int idtipoiva, String nombre, Set<Entrada> entradas) {
		this.idtipoiva = idtipoiva;
		this.nombre = nombre;
		this.entradas = entradas;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idtipoiva", unique = true, nullable = false)
	public int getIdtipoiva() {
		return this.idtipoiva;
	}

	public void setIdtipoiva(int idtipoiva) {
		this.idtipoiva = idtipoiva;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddTiposIva")
	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
