package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdTipoEntrada generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_entrada", catalog = "jbossforge")
public class DdTipoEntrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6930581924254393809L;
	private int idtipoentrada;
	private String nombre;

	public DdTipoEntrada() {
	}

	public DdTipoEntrada(int idtipoentrada, String nombre) {
		this.idtipoentrada = idtipoentrada;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idtipoentrada", unique = true, nullable = false)
	public int getIdtipoentrada() {
		return this.idtipoentrada;
	}

	public void setIdtipoentrada(int idtipoentrada) {
		this.idtipoentrada = idtipoentrada;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
