package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DdTipoEntrada generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_entrada", catalog = "jbossforge")
@XmlRootElement
public class DdTipoEntrada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -855669790331252791L;
	private int idtipoentrada;
	private String nombre;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public DdTipoEntrada() {
	}

	public DdTipoEntrada(int idtipoentrada, String nombre) {
		this.idtipoentrada = idtipoentrada;
		this.nombre = nombre;
	}
	public DdTipoEntrada(int idtipoentrada, String nombre, Set<Entrada> entradas) {
		this.idtipoentrada = idtipoentrada;
		this.nombre = nombre;
		this.entradas = entradas;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idtipoentrada", unique = true, nullable = false)
	public int getIdtipoentrada() {
		return this.idtipoentrada;
	}

	public void setIdtipoentrada(int idtipoentrada) {
		this.idtipoentrada = idtipoentrada;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ddTipoEntrada")
	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
