package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdTipoEvento generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_evento", catalog = "jbossforge")
public class DdTipoEvento implements java.io.Serializable {

	private static final long serialVersionUID = 4663081648643131014L;
	private int idTipoEvento;
	private String tipoEvento;

	public DdTipoEvento() {
	}

	public DdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}
	public DdTipoEvento(int idTipoEvento, String tipoEvento) {
		this.idTipoEvento = idTipoEvento;
		this.tipoEvento = tipoEvento;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idtipoevento", unique = true, nullable = false)
	public int getIdTipoEvento() {
		return this.idTipoEvento;
	}

	public void setIdTipoEvento(int idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	@Column(name = "nombre", length = 100)
	public String getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(String tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

}
