package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdFormapago generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_complemento", catalog = "jbossforge")
public class DdTipoComplemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5169190954994893032L;
	/**
	 * 
	 */
	
	private int idcomplemento;
	private String nombre;
	private BigDecimal precio;
	private String descripcion;


	public DdTipoComplemento() {
		nombre = null;
		precio = new BigDecimal(0);
		descripcion = null;
	}

	

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idcomplemento", unique = true, nullable = false)
	public int getIdcomplemento() {
		return this.idcomplemento;
	}

	public void setIdcomplemento(int idcomplemento) {
		this.idcomplemento = idcomplemento;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}
	public String getDescripcion() {
		return descripcion;
	}



	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
