package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DdTiposIva generated by hbm2java
 */
@Entity
@Table(name = "dd_tipos_iva", catalog = "jbossforge")
public class DdTiposIva implements java.io.Serializable {

	private static final long serialVersionUID = -1784803521447790460L;
	private int idtipoiva;
	private String nombre;

	public DdTiposIva() {
	}

	public DdTiposIva(int idtipoiva) {
		this.idtipoiva = idtipoiva;
	}
	public DdTiposIva(int idtipoiva, String nombre) {
		this.idtipoiva = idtipoiva;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idtipoiva", unique = true, nullable = false)
	public int getIdtipoiva() {
		return this.idtipoiva;
	}

	public void setIdtipoiva(int idtipoiva) {
		this.idtipoiva = idtipoiva;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
