package org.dinamizadores.dinaeventos.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DdTipoEntrada generated by hbm2java
 */
@Entity
@Table(name = "dd_tipo_entrada", catalog = "jbossforge")
public class DdTipoEntrada implements java.io.Serializable {

	private static final long serialVersionUID = -6930581924254393809L;
	private int idtipoentrada;
	private String nombre;
	private BigDecimal precio;
	private Integer cantidad;
	private Integer idEvento;
	private Evento evento;
    private Boolean sobreVenta;
    private Integer maxPorPedido;
    private String canalDeVentas;
    private Date fechaInicioVenta;
    private Date fechaFinVenta;
    private Boolean activa;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);
	
	
    public DdTipoEntrada() {
    }

    public DdTipoEntrada(Evento evento, String nombre, BigDecimal precio, Integer cantidad, Boolean sobreVenta, Integer maxPorPedido, String canalDeVentas, Date fechaInicioVenta, Date fechaFinVenta, Set<Entrada> entradas) {
       this.evento = evento;
       this.nombre = nombre;
       this.precio = precio;
       this.cantidad = cantidad;
       this.sobreVenta = sobreVenta;
       this.maxPorPedido = maxPorPedido;
       this.canalDeVentas = canalDeVentas;
       this.fechaInicioVenta = fechaInicioVenta;
       this.fechaFinVenta = fechaFinVenta;
       this.entradas = entradas;
    }    

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idtipoentrada", unique = true, nullable = false)
	public int getIdtipoentrada() {
		return this.idtipoentrada;
	}

	public void setIdtipoentrada(int idtipoentrada) {
		this.idtipoentrada = idtipoentrada;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "precio", nullable = true)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}
	
	@Column(name = "cantidad")
	public Integer getCantidad() {
		return cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}
	
	@Column(name="idevento")
	public Integer getIdEvento() {
		return idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idevento", insertable = false, updatable = false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    
    @Column(name="sobreventa")
    public Boolean getSobreVenta() {
        return this.sobreVenta;
    }
    
    public void setSobreVenta(Boolean sobreVenta) {
        this.sobreVenta = sobreVenta;
    }

    
    @Column(name="maxporpedido")
    public Integer getMaxPorPedido() {
        return this.maxPorPedido;
    }
    
    public void setMaxPorPedido(Integer maxPorPedido) {
        this.maxPorPedido = maxPorPedido;
    }

    
    @Column(name="canaldeventas", length=100)
    public String getCanalDeVentas() {
        return this.canalDeVentas;
    }
    
    public void setCanalDeVentas(String canalDeVentas) {
        this.canalDeVentas = canalDeVentas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechainicioventa", length=10)
    public Date getFechaInicioVenta() {
        return this.fechaInicioVenta;
    }
    
    public void setFechaInicioVenta(Date fechaInicioVenta) {
        this.fechaInicioVenta = fechaInicioVenta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechafinventa", length=10)
    public Date getFechaFinVenta() {
        return this.fechaFinVenta;
    }
    
    public void setFechaFinVenta(Date fechaFinVenta) {
        this.fechaFinVenta = fechaFinVenta;
    }
    
    @Column(name ="activa")
    public Boolean getActiva() {
		return activa;
	}

	public void setActiva(Boolean activa) {
		this.activa = activa;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="ddTipoEntrada")
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }

}
