package org.dinamizadores.dinaeventos.model;
// Generated 23-jun-2016 9:47:12 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GlobalCodigospostales generated by hbm2java
 */
@Entity
@Table(name="global_codigospostales" ,catalog="jbossforge")
public class GlobalCodigospostales  implements java.io.Serializable {

	private static final long serialVersionUID = 3272568428662816916L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idcodigopostal", unique=true, nullable=false)
	private int idcodigopostal;
    @Column(name="idprovincia")
    private Integer idprovincia;
    @Column(name="codigo", length=5)
    private String codigo;
    @Column(name="localidad")
    private String localidad;
    @ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="idProvincia", insertable=false, updatable=false)
    private GlobalProvincias provincia;

    public GlobalCodigospostales() {
    }
	
    public GlobalCodigospostales(int idcodigopostal) {
        this.idcodigopostal = idcodigopostal;
    }
    public GlobalCodigospostales(int idcodigopostal, Integer idprovincia, String codigo, String localidad) {
       this.idcodigopostal = idcodigopostal;
       this.idprovincia = idprovincia;
       this.codigo = codigo;
       this.localidad = localidad;
    }
   
    public int getIdcodigopostal() {
        return this.idcodigopostal;
    }
    
    public void setIdcodigopostal(int idcodigopostal) {
        this.idcodigopostal = idcodigopostal;
    }

    public Integer getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(Integer idprovincia) {
        this.idprovincia = idprovincia;
    }

    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

	public GlobalProvincias getProvincia() {
		return provincia;
	}

	public void setProvincia(GlobalProvincias provincia) {
		this.provincia = provincia;
	}

}


