package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Organizadores generated by hbm2java
 */
@Entity
@Table(name = "organizadores", catalog = "jbossforge", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Organizadores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3771450537753481435L;
	private int idorganizador;
	private String nombre;
	private String direccion;
	private String descripcion;
	private String enlacefb;
	private String enlacetw;
	private String email;
	private String telefono;
	private String password;
	private String cuentacorriente;
	private String iban;
	private Integer idcodigopostal;

	public Organizadores() {
	}

	public Organizadores(int idorganizador, String email, String password) {
		this.idorganizador = idorganizador;
		this.email = email;
		this.password = password;
	}
	public Organizadores(int idorganizador, String nombre, String direccion,
			String descripcion, String enlacefb, String enlacetw, String email,
			String telefono, String password, String cuentacorriente,
			String iban, Integer idcodigopostal) {
		this.idorganizador = idorganizador;
		this.nombre = nombre;
		this.direccion = direccion;
		this.descripcion = descripcion;
		this.enlacefb = enlacefb;
		this.enlacetw = enlacetw;
		this.email = email;
		this.telefono = telefono;
		this.password = password;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.idcodigopostal = idcodigopostal;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idorganizador", unique = true, nullable = false)
	public int getIdorganizador() {
		return this.idorganizador;
	}

	public void setIdorganizador(int idorganizador) {
		this.idorganizador = idorganizador;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "enlacefb")
	public String getEnlacefb() {
		return this.enlacefb;
	}

	public void setEnlacefb(String enlacefb) {
		this.enlacefb = enlacefb;
	}

	@Column(name = "enlacetw")
	public String getEnlacetw() {
		return this.enlacetw;
	}

	public void setEnlacetw(String enlacetw) {
		this.enlacetw = enlacetw;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cuentacorriente", length = 45)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 45)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "idcodigopostal")
	public Integer getIdcodigopostal() {
		return this.idcodigopostal;
	}

	public void setIdcodigopostal(Integer idcodigopostal) {
		this.idcodigopostal = idcodigopostal;
	}

}
