package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Organizadores generated by hbm2java
 */
@Entity
@Table(name = "organizadores", catalog = "jbossforge")
public class Organizadores implements java.io.Serializable {

	private static final long serialVersionUID = 3771450537753481435L;
	private int idorganizador;
	private String cuentacorriente;
	private String iban;
	private Integer idUsuario;
	private Usuario usuario;

	public Organizadores() {
		this.usuario = null;
		this.idUsuario = null;
	}
	
	public Organizadores(int idorganizador, String cuentacorriente, String iban, Integer idUsuario, Usuario usuario) {
		super();
		this.idorganizador = idorganizador;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.idUsuario = idUsuario;
		this.usuario = usuario;
	}



	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idorganizador", unique = true, nullable = false)
	public int getIdorganizador() {
		return this.idorganizador;
	}

	public void setIdorganizador(int idorganizador) {
		this.idorganizador = idorganizador;
	}

	@Column(name = "cuentacorriente", length = 20)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 34)
	public String getIban() {
		return this.iban;
	}
	
	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "idusuario", unique = true)
	public Integer getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	
	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "idusuario", insertable = false, updatable = false)
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
}
