package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Organizador generated by hbm2java
 */
@Entity
@Table(name = "organizador", catalog = "jbossforge")
@XmlRootElement
public class Organizador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5156480790838710907L;
	private int idorganizador;
	private GlobalCodigopostal globalCodigopostal;
	private String nombre;
	private String direccion;
	private String descripcion;
	private String enlacefb;
	private String enlacetw;
	private String email;
	private String telefono;
	private String password;
	private String cuentacorriente;
	private String iban;
	private Set<RrppJefe> rrppJefes = new HashSet<RrppJefe>(0);
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public Organizador() {
	}

	public Organizador(int idorganizador,
			GlobalCodigopostal globalCodigopostal, String password) {
		this.idorganizador = idorganizador;
		this.globalCodigopostal = globalCodigopostal;
		this.password = password;
	}
	public Organizador(int idorganizador,
			GlobalCodigopostal globalCodigopostal, String nombre,
			String direccion, String descripcion, String enlacefb,
			String enlacetw, String email, String telefono, String password,
			String cuentacorriente, String iban, Set<RrppJefe> rrppJefes,
			Set<Evento> eventos) {
		this.idorganizador = idorganizador;
		this.globalCodigopostal = globalCodigopostal;
		this.nombre = nombre;
		this.direccion = direccion;
		this.descripcion = descripcion;
		this.enlacefb = enlacefb;
		this.enlacetw = enlacetw;
		this.email = email;
		this.telefono = telefono;
		this.password = password;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.rrppJefes = rrppJefes;
		this.eventos = eventos;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idorganizador", unique = true, nullable = false)
	public int getIdorganizador() {
		return this.idorganizador;
	}

	public void setIdorganizador(int idorganizador) {
		this.idorganizador = idorganizador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcodigopostal", nullable = false)
	public GlobalCodigopostal getGlobalCodigopostal() {
		return this.globalCodigopostal;
	}

	public void setGlobalCodigopostal(GlobalCodigopostal globalCodigopostal) {
		this.globalCodigopostal = globalCodigopostal;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "enlacefb", length = 45)
	public String getEnlacefb() {
		return this.enlacefb;
	}

	public void setEnlacefb(String enlacefb) {
		this.enlacefb = enlacefb;
	}

	@Column(name = "enlacetw", length = 45)
	public String getEnlacetw() {
		return this.enlacetw;
	}

	public void setEnlacetw(String enlacetw) {
		this.enlacetw = enlacetw;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cuentacorriente", length = 45)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 45)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizador")
	public Set<RrppJefe> getRrppJefes() {
		return this.rrppJefes;
	}

	public void setRrppJefes(Set<RrppJefe> rrppJefes) {
		this.rrppJefes = rrppJefes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizador")
	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
