package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Patrocinador generated by hbm2java
 */
@Entity
@Table(name = "patrocinador", catalog = "jbossforge")
@XmlRootElement
public class Patrocinador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -338721678686586442L;
	private int idpatrocinador;
	private GlobalCodigopostal globalCodigopostal;
	private String nombre;
	private String direccion;
	private String telefono;
	private String email;
	private String cuentacorriente;
	private String iban;
	private Set<Evento> eventos = new HashSet<Evento>(0);

	public Patrocinador() {
	}

	public Patrocinador(int idpatrocinador,
			GlobalCodigopostal globalCodigopostal) {
		this.idpatrocinador = idpatrocinador;
		this.globalCodigopostal = globalCodigopostal;
	}
	public Patrocinador(int idpatrocinador,
			GlobalCodigopostal globalCodigopostal, String nombre,
			String direccion, String telefono, String email,
			String cuentacorriente, String iban, Set<Evento> eventos) {
		this.idpatrocinador = idpatrocinador;
		this.globalCodigopostal = globalCodigopostal;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.eventos = eventos;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idpatrocinador", unique = true, nullable = false)
	public int getIdpatrocinador() {
		return this.idpatrocinador;
	}

	public void setIdpatrocinador(int idpatrocinador) {
		this.idpatrocinador = idpatrocinador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcodigopostal", nullable = false)
	public GlobalCodigopostal getGlobalCodigopostal() {
		return this.globalCodigopostal;
	}

	public void setGlobalCodigopostal(GlobalCodigopostal globalCodigopostal) {
		this.globalCodigopostal = globalCodigopostal;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cuentacorriente", length = 45)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 45)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dd_patrocinador_evento", catalog = "jbossforge", joinColumns = {@JoinColumn(name = "idpatrocinador", nullable = false, updatable = false)}, inverseJoinColumns = {@JoinColumn(name = "idevento", nullable = false, updatable = false)})
	public Set<Evento> getEventos() {
		return this.eventos;
	}

	public void setEventos(Set<Evento> eventos) {
		this.eventos = eventos;
	}

}
