package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name = "permisos", catalog = "jbossforge")
@XmlRootElement
public class Permisos implements java.io.Serializable {

	private static final long serialVersionUID = 4924890478911074919L;
	private int idpermisos;
	private String nombre;
	private Set<Roles> roleses = new HashSet<Roles>(0);

	public Permisos() {
	}

	public Permisos(int idpermisos) {
		this.idpermisos = idpermisos;
	}
	public Permisos(int idpermisos, String nombre, Set<Roles> roleses) {
		this.idpermisos = idpermisos;
		this.nombre = nombre;
		this.roleses = roleses;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idpermisos", unique = true, nullable = false)
	public int getIdpermisos() {
		return this.idpermisos;
	}

	public void setIdpermisos(int idpermisos) {
		this.idpermisos = idpermisos;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "permisoses")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
