package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name = "permisos", catalog = "jbossforge")
public class Permisos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7552776053878177082L;
	private int idpermisos;
	private String nombre;

	public Permisos() {
	}

	public Permisos(int idpermisos) {
		this.idpermisos = idpermisos;
	}
	public Permisos(int idpermisos, String nombre) {
		this.idpermisos = idpermisos;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idpermisos", unique = true, nullable = false)
	public int getIdpermisos() {
		return this.idpermisos;
	}

	public void setIdpermisos(int idpermisos) {
		this.idpermisos = idpermisos;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
