package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Redessociales generated by hbm2java
 */
@Entity
@Table(name = "redessociales", catalog = "jbossforge")
public class Redessociales implements java.io.Serializable {

	private static final long serialVersionUID = 8114825636505298077L;
	private int idredessociales;
	private String enlacePerfil;
	private String token;
	private String enlaceFoto;
	private String idUser;
	private String redSocial;

	public Redessociales(int idredessociales, String enlacePerfil, String token, String enlaceFoto, String idUser,
			String redSocial) {
		super();
		this.idredessociales = idredessociales;
		this.enlacePerfil = enlacePerfil;
		this.token = token;
		this.enlaceFoto = enlaceFoto;
		this.idUser = idUser;
		this.redSocial = redSocial;
	}

	public Redessociales() {
	}

	public Redessociales(int idredessociales) {
		this.idredessociales = idredessociales;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idredessociales", unique = true, nullable = false)
	public int getIdredessociales() {
		return this.idredessociales;
	}

	public void setIdredessociales(int idredessociales) {
		this.idredessociales = idredessociales;
	}

	@Column(name = "enlaceperfil", length = 500)
	public String getEnlacePerfil() {
		return this.enlacePerfil;
	}

	public void setEnlacePerfil(String enlacePerfil) {
		this.enlacePerfil = enlacePerfil;
	}

	@Column(name = "token", length = 500)
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "enlacefoto", length = 500)
	public String getEnlaceFoto() {
		return enlaceFoto;
	}

	public void setEnlaceFoto(String enlaceFoto) {
		this.enlaceFoto = enlaceFoto;
	}

	@Column(name = "redsocial", length = 100)
	public String getRedSocial() {
		return redSocial;
	}

	public void setRedSocial(String redSocial) {
		this.redSocial = redSocial;
	}

	@Column(name = "iduser", length = 255)
	public String getIdUser() {
		return idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}
	
	
}
