package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Redessociales generated by hbm2java
 */
@Entity
@Table(name = "redessociales", catalog = "jbossforge")
@XmlRootElement
public class Redessociales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4317303242818987910L;
	private int idredessociales;
	private String enlace;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Redessociales() {
	}

	public Redessociales(int idredessociales) {
		this.idredessociales = idredessociales;
	}
	public Redessociales(int idredessociales, String enlace,
			Set<Usuario> usuarios) {
		this.idredessociales = idredessociales;
		this.enlace = enlace;
		this.usuarios = usuarios;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idredessociales", unique = true, nullable = false)
	public int getIdredessociales() {
		return this.idredessociales;
	}

	public void setIdredessociales(int idredessociales) {
		this.idredessociales = idredessociales;
	}

	@Column(name = "enlace", length = 45)
	public String getEnlace() {
		return this.enlace;
	}

	public void setEnlace(String enlace) {
		this.enlace = enlace;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "redessociales")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
