package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "jbossforge")
public class Roles implements java.io.Serializable {

	private static final long serialVersionUID = -2355534628473632039L;
	private int idrol;
	private String nombre;
	private Set<Permisos> permisos = new HashSet<Permisos>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	
	public Roles() {
	}

	public Roles(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idrol", unique = true, nullable = false)
	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy = "roles")
	public Set<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="roles_permisos", catalog="jbossforge", joinColumns = { 
        @JoinColumn(name="idrol", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idpermisos", nullable=false, updatable=false) })
    public Set<Permisos> getPermisos() {
        return this.permisos;
    }

	public void setPermisos(Set<Permisos> permisos) {
		this.permisos = permisos;
	}
	
}
