package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RolesPermisos generated by hbm2java
 */
@Entity
@Table(name = "roles_permisos", catalog = "jbossforge")
public class RolesPermisos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7747526163822589907L;
	private RolesPermisosId id;

	public RolesPermisos() {
	}

	public RolesPermisos(RolesPermisosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idrol", column = @Column(name = "idrol", nullable = false)),
			@AttributeOverride(name = "idpermisos", column = @Column(name = "idpermisos", nullable = false))})
	public RolesPermisosId getId() {
		return this.id;
	}

	public void setId(RolesPermisosId id) {
		this.id = id;
	}

}
