package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * RrppJefes generated by hbm2java
 */
@Entity
@Table(name = "rrpp_jefes", catalog = "jbossforge")
public class RrppJefes implements java.io.Serializable {

	private static final long serialVersionUID = -2647515921108590406L;
	private int idrrppJefe;
	private Integer idOrganizador;
	private Organizadores organizador;
	private Integer idUsuario;
	private Usuario usuario;
	private Integer limiteEntradas;
	private String codigoPromocional;
    private Set<RrppMinion> rrppMinions = new HashSet<RrppMinion>(0);
    private Set<DdRrppJefeEntrada> ddRrppJefeEntradas = new HashSet<DdRrppJefeEntrada>(0);
    private Set<Evento> eventos = new HashSet<Evento>(0);

	public RrppJefes() {
	}

	public RrppJefes(int idrrppJefe) {
		this.idrrppJefe = idrrppJefe;
	}
	public RrppJefes(int idrrppJefe,Integer idOrganizador, Integer idUsuario, Integer limiteEntradas,
			String codigoPromocional) {
		this.idrrppJefe = idrrppJefe;
		this.idOrganizador = idOrganizador;
		this.idUsuario = idUsuario;
		this.limiteEntradas = limiteEntradas;
		this.codigoPromocional = codigoPromocional;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idrrpp_jefe", unique = true, nullable = false)
	public int getIdrrppJefe() {
		return this.idrrppJefe;
	}

	public void setIdrrppJefe(int idrrppJefe) {
		this.idrrppJefe = idrrppJefe;
	}

	@Column(name = "idorganizador")
	public Integer getIdOrganizador() {
		return this.idOrganizador;
	}

	public void setIdOrganizador(Integer idOrganizador) {
		this.idOrganizador = idOrganizador;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idorganizador", insertable = false, updatable = false)
    public Organizadores getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(Organizadores organizador) {
        this.organizador = organizador;
    }
	
	@Column(name = "idUsuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="idUsuario", insertable=false, updatable=false)
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "limite_entradas")
	public Integer getLimiteEntradas() {
		return this.limiteEntradas;
	}

	public void setLimiteEntradas(Integer limiteEntradas) {
		this.limiteEntradas = limiteEntradas;
	}

	@Column(name = "codigo_promocional", length = 100)
	public String getCodigoPromocional() {
		return this.codigoPromocional;
	}

	public void setCodigoPromocional(String codigoPromocional) {
		this.codigoPromocional = codigoPromocional;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="rrppJefes")
    public Set<RrppMinion> getRrppMinions() {
        return this.rrppMinions;
    }
    
    public void setRrppMinions(Set<RrppMinion> rrppMinions) {
        this.rrppMinions = rrppMinions;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="rrppJefes")
    public Set<DdRrppJefeEntrada> getDdRrppJefeEntradas() {
        return this.ddRrppJefeEntradas;
    }
    
    public void setDdRrppJefeEntradas(Set<DdRrppJefeEntrada> ddRrppJefeEntradas) {
        this.ddRrppJefeEntradas = ddRrppJefeEntradas;
    }

    @ManyToMany(fetch=FetchType.LAZY, mappedBy="rrppJefes")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }


}
