package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RrppJefeHasEntrada generated by hbm2java
 */
@Entity
@Table(name="rrpp_jefe_has_entrada"
    ,catalog="jbossforge"
)
public class RrppJefeHasEntrada  implements java.io.Serializable {

	private static final long serialVersionUID = 7401610720471967245L;
	private RrppJefeHasEntradaId id;
    private Entrada entrada;
    private RrppJefe rrppJefe;
    private RrppMinion rrppMinion;

    public RrppJefeHasEntrada() {
    }

	
    public RrppJefeHasEntrada(RrppJefeHasEntradaId id, Entrada entrada, RrppJefe rrppJefe) {
        this.id = id;
        this.entrada = entrada;
        this.rrppJefe = rrppJefe;
    }
    public RrppJefeHasEntrada(RrppJefeHasEntradaId id, Entrada entrada, RrppJefe rrppJefe, RrppMinion rrppMinion) {
       this.id = id;
       this.entrada = entrada;
       this.rrppJefe = rrppJefe;
       this.rrppMinion = rrppMinion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="rrppJefeIdrrppJefe", column=@Column(name="rrpp_jefe_idrrpp_jefe", nullable=false) ), 
        @AttributeOverride(name="entradaIdentrada", column=@Column(name="entrada_identrada", nullable=false) ) } )
    public RrppJefeHasEntradaId getId() {
        return this.id;
    }
    
    public void setId(RrppJefeHasEntradaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entrada_identrada", nullable=false, insertable=false, updatable=false)
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rrpp_jefe_idrrpp_jefe", nullable=false, insertable=false, updatable=false)
    public RrppJefe getRrppJefe() {
        return this.rrppJefe;
    }
    
    public void setRrppJefe(RrppJefe rrppJefe) {
        this.rrppJefe = rrppJefe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rrpp_minion_idrrpp_minion")
    public RrppMinion getRrppMinion() {
        return this.rrppMinion;
    }
    
    public void setRrppMinion(RrppMinion rrppMinion) {
        this.rrppMinion = rrppMinion;
    }




}


