package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RrppJefeHasEntradaId generated by hbm2java
 */
@Embeddable
public class RrppJefeHasEntradaId  implements java.io.Serializable {

	private static final long serialVersionUID = 233118576439673879L;
	private int rrppJefeIdrrppJefe;
     private int entradaIdentrada;

    public RrppJefeHasEntradaId() {
    }

    public RrppJefeHasEntradaId(int rrppJefeIdrrppJefe, int entradaIdentrada) {
       this.rrppJefeIdrrppJefe = rrppJefeIdrrppJefe;
       this.entradaIdentrada = entradaIdentrada;
    }
   


    @Column(name="rrpp_jefe_idrrpp_jefe", nullable=false)
    public int getRrppJefeIdrrppJefe() {
        return this.rrppJefeIdrrppJefe;
    }
    
    public void setRrppJefeIdrrppJefe(int rrppJefeIdrrppJefe) {
        this.rrppJefeIdrrppJefe = rrppJefeIdrrppJefe;
    }


    @Column(name="entrada_identrada", nullable=false)
    public int getEntradaIdentrada() {
        return this.entradaIdentrada;
    }
    
    public void setEntradaIdentrada(int entradaIdentrada) {
        this.entradaIdentrada = entradaIdentrada;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RrppJefeHasEntradaId) ) return false;
		 RrppJefeHasEntradaId castOther = ( RrppJefeHasEntradaId ) other; 
         
		 return (this.getRrppJefeIdrrppJefe()==castOther.getRrppJefeIdrrppJefe())
 && (this.getEntradaIdentrada()==castOther.getEntradaIdentrada());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRrppJefeIdrrppJefe();
         result = 37 * result + this.getEntradaIdentrada();
         return result;
   }   


}


