package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RrppMinion generated by hbm2java
 */
@Entity
@Table(name = "rrpp_minion", catalog = "jbossforge")
public class RrppMinion implements java.io.Serializable {

	private static final long serialVersionUID = 1697250336808658251L;
	private int idrrppMinion;
	private Integer idjefe;
	private RrppJefes rrppJefes;
	private Integer idUsuario;
	private Usuario usuario;
	private Integer limiteEntradas;
	private String coigoPromocional;
	private Set<DdRrppJefeEntrada> ddRrppJefeEntradas = new HashSet<DdRrppJefeEntrada>(0);
	
	public RrppMinion() {
	}

	public RrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}
	public RrppMinion(int idrrppMinion, Integer idjefe, Integer idUsuario,
			Integer limiteEntradas, String coigoPromocional) {
		this.idrrppMinion = idrrppMinion;
		this.idjefe = idjefe;
		this.idUsuario = idUsuario;
		this.limiteEntradas = limiteEntradas;
		this.coigoPromocional = coigoPromocional;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idrrpp_minion", unique = true, nullable = false)
	public int getIdrrppMinion() {
		return this.idrrppMinion;
	}

	public void setIdrrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}

	@Column(name = "idjefe")
	public Integer getIdjefe() {
		return this.idjefe;
	}

	public void setIdjefe(Integer idjefe) {
		this.idjefe = idjefe;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idjefe", insertable = false, updatable = false)
    public RrppJefes getRrppJefes() {
        return this.rrppJefes;
    }
    
    public void setRrppJefes(RrppJefes rrppJefes) {
        this.rrppJefes = rrppJefes;
    }
	
	@Column(name = "idUsuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", updatable = false, insertable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }
	
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "limite_entradas")
	public Integer getLimiteEntradas() {
		return this.limiteEntradas;
	}

	public void setLimiteEntradas(Integer limiteEntradas) {
		this.limiteEntradas = limiteEntradas;
	}

	@Column(name = "coigo_promocional", length = 100)
	public String getCoigoPromocional() {
		return this.coigoPromocional;
	}

	public void setCoigoPromocional(String coigoPromocional) {
		this.coigoPromocional = coigoPromocional;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="rrppMinion")
    public Set<DdRrppJefeEntrada> getDdRrppJefeEntradas() {
        return this.ddRrppJefeEntradas;
    }
    
    public void setDdRrppJefeEntradas(Set<DdRrppJefeEntrada> ddRrppJefeEntradas) {
        this.ddRrppJefeEntradas = ddRrppJefeEntradas;
    }

}
