package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RrppJefes generated by hbm2java
 */
@Entity
@Table(name = "rrpp_jefes", catalog = "jbossforge")
public class RrppJefes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2647515921108590406L;
	private int idrrppJefe;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String telefono;
	private Integer idorganizador;
	private Integer limiteEntradas;
	private String codigoPromocional;

	public RrppJefes() {
	}

	public RrppJefes(int idrrppJefe) {
		this.idrrppJefe = idrrppJefe;
	}
	public RrppJefes(int idrrppJefe, String nombre, String apellido1,
			String apellido2, String email, String telefono,
			Integer idorganizador, Integer limiteEntradas,
			String codigoPromocional) {
		this.idrrppJefe = idrrppJefe;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
		this.idorganizador = idorganizador;
		this.limiteEntradas = limiteEntradas;
		this.codigoPromocional = codigoPromocional;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idrrpp_jefe", unique = true, nullable = false)
	public int getIdrrppJefe() {
		return this.idrrppJefe;
	}

	public void setIdrrppJefe(int idrrppJefe) {
		this.idrrppJefe = idrrppJefe;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "idorganizador")
	public Integer getIdorganizador() {
		return this.idorganizador;
	}

	public void setIdorganizador(Integer idorganizador) {
		this.idorganizador = idorganizador;
	}

	@Column(name = "limite_entradas")
	public Integer getLimiteEntradas() {
		return this.limiteEntradas;
	}

	public void setLimiteEntradas(Integer limiteEntradas) {
		this.limiteEntradas = limiteEntradas;
	}

	@Column(name = "codigo_promocional", length = 100)
	public String getCodigoPromocional() {
		return this.codigoPromocional;
	}

	public void setCodigoPromocional(String codigoPromocional) {
		this.codigoPromocional = codigoPromocional;
	}

}
