package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RrppMinion generated by hbm2java
 */
@Entity
@Table(name = "rrpp_minion", catalog = "jbossforge")
public class RrppMinion implements java.io.Serializable {

	private static final long serialVersionUID = 1697250336808658251L;
	private int idrrppMinion;
	private Integer idjefe;
	private Integer idUsuario;
	private Integer limiteEntradas;
	private String coigoPromocional;

	public RrppMinion() {
	}

	public RrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}
	public RrppMinion(int idrrppMinion, Integer idjefe, Integer idUsuario,
			Integer limiteEntradas, String coigoPromocional) {
		this.idrrppMinion = idrrppMinion;
		this.idjefe = idjefe;
		this.idUsuario = idUsuario;
		this.limiteEntradas = limiteEntradas;
		this.coigoPromocional = coigoPromocional;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idrrpp_minion", unique = true, nullable = false)
	public int getIdrrppMinion() {
		return this.idrrppMinion;
	}

	public void setIdrrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}

	@Column(name = "idjefe")
	public Integer getIdjefe() {
		return this.idjefe;
	}

	public void setIdjefe(Integer idjefe) {
		this.idjefe = idjefe;
	}
	
	@Column(name = "idUsuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "limite_entradas")
	public Integer getLimiteEntradas() {
		return this.limiteEntradas;
	}

	public void setLimiteEntradas(Integer limiteEntradas) {
		this.limiteEntradas = limiteEntradas;
	}

	@Column(name = "coigo_promocional", length = 100)
	public String getCoigoPromocional() {
		return this.coigoPromocional;
	}

	public void setCoigoPromocional(String coigoPromocional) {
		this.coigoPromocional = coigoPromocional;
	}

}
