package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RrppMinion generated by hbm2java
 */
@Entity
@Table(name = "rrpp_minion", catalog = "jbossforge")
public class RrppMinion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1697250336808658251L;
	private int idrrppMinion;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String telefono;
	private Integer idjefe;
	private Integer limiteEntradas;
	private String coigoPromocional;

	public RrppMinion() {
	}

	public RrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}
	public RrppMinion(int idrrppMinion, String nombre, String apellido1,
			String apellido2, String email, String telefono, Integer idjefe,
			Integer limiteEntradas, String coigoPromocional) {
		this.idrrppMinion = idrrppMinion;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
		this.idjefe = idjefe;
		this.limiteEntradas = limiteEntradas;
		this.coigoPromocional = coigoPromocional;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idrrpp_minion", unique = true, nullable = false)
	public int getIdrrppMinion() {
		return this.idrrppMinion;
	}

	public void setIdrrppMinion(int idrrppMinion) {
		this.idrrppMinion = idrrppMinion;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "idjefe")
	public Integer getIdjefe() {
		return this.idjefe;
	}

	public void setIdjefe(Integer idjefe) {
		this.idjefe = idjefe;
	}

	@Column(name = "limite_entradas")
	public Integer getLimiteEntradas() {
		return this.limiteEntradas;
	}

	public void setLimiteEntradas(Integer limiteEntradas) {
		this.limiteEntradas = limiteEntradas;
	}

	@Column(name = "coigo_promocional", length = 100)
	public String getCoigoPromocional() {
		return this.coigoPromocional;
	}

	public void setCoigoPromocional(String coigoPromocional) {
		this.coigoPromocional = coigoPromocional;
	}

}
