package org.dinamizadores.dinaeventos.model;
// Generated 06-jun-2016 19:44:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", catalog = "jbossforge")
@XmlRootElement
public class Sexo implements java.io.Serializable {

	private static final long serialVersionUID = -7982297134552540073L;
	private int idsexo;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Sexo() {
	}

	public Sexo(int idsexo, String nombre) {
		this.idsexo = idsexo;
		this.nombre = nombre;
	}
	public Sexo(int idsexo, String nombre, Set<Usuario> usuarios) {
		this.idsexo = idsexo;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idsexo", unique = true, nullable = false)
	public int getIdsexo() {
		return this.idsexo;
	}

	public void setIdsexo(int idsexo) {
		this.idsexo = idsexo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
