package org.dinamizadores.dinaeventos.model;
// Generated 07-jun-2016 22:29:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "jbossforge")
@XmlRootElement
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2027988858915595039L;
	private int idusuario;
	private DdSexo ddSexo;
	private GlobalCodigopostal globalCodigopostal;
	private Redessociales redessociales;
	private Roles roles;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String telefono;
	private Date fechanac;
	private String direccion;
	private byte[] fotoperfil;
	private String password;
	private String cuentacorriente;
	private String iban;
	private Boolean bloqueado;
	private Boolean activo;
	private Date ultimologin;
	private Set<Entrada> entradas = new HashSet<Entrada>(0);

	public Usuario() {
	}

	public Usuario(int idusuario, DdSexo ddSexo,
			GlobalCodigopostal globalCodigopostal, Redessociales redessociales,
			Roles roles, String apellido1, String password) {
		this.idusuario = idusuario;
		this.ddSexo = ddSexo;
		this.globalCodigopostal = globalCodigopostal;
		this.redessociales = redessociales;
		this.roles = roles;
		this.apellido1 = apellido1;
		this.password = password;
	}
	public Usuario(int idusuario, DdSexo ddSexo,
			GlobalCodigopostal globalCodigopostal, Redessociales redessociales,
			Roles roles, String nombre, String apellido1, String apellido2,
			String email, String telefono, Date fechanac, String direccion,
			byte[] fotoperfil, String password, String cuentacorriente,
			String iban, Boolean bloqueado, Boolean activo, Date ultimologin,
			Set<Entrada> entradas) {
		this.idusuario = idusuario;
		this.ddSexo = ddSexo;
		this.globalCodigopostal = globalCodigopostal;
		this.redessociales = redessociales;
		this.roles = roles;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
		this.fechanac = fechanac;
		this.direccion = direccion;
		this.fotoperfil = fotoperfil;
		this.password = password;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.bloqueado = bloqueado;
		this.activo = activo;
		this.ultimologin = ultimologin;
		this.entradas = entradas;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsexo", nullable = false)
	public DdSexo getDdSexo() {
		return this.ddSexo;
	}

	public void setDdSexo(DdSexo ddSexo) {
		this.ddSexo = ddSexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcodigopostal", nullable = false)
	public GlobalCodigopostal getGlobalCodigopostal() {
		return this.globalCodigopostal;
	}

	public void setGlobalCodigopostal(GlobalCodigopostal globalCodigopostal) {
		this.globalCodigopostal = globalCodigopostal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idredessociales", nullable = false)
	public Redessociales getRedessociales() {
		return this.redessociales;
	}

	public void setRedessociales(Redessociales redessociales) {
		this.redessociales = redessociales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanac", length = 10)
	public Date getFechanac() {
		return this.fechanac;
	}

	public void setFechanac(Date fechanac) {
		this.fechanac = fechanac;
	}

	@Column(name = "direccion", length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "fotoperfil")
	public byte[] getFotoperfil() {
		return this.fotoperfil;
	}

	public void setFotoperfil(byte[] fotoperfil) {
		this.fotoperfil = fotoperfil;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cuentacorriente", length = 45)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 45)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "bloqueado")
	public Boolean getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(Boolean bloqueado) {
		this.bloqueado = bloqueado;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimologin", length = 10)
	public Date getUltimologin() {
		return this.ultimologin;
	}

	public void setUltimologin(Date ultimologin) {
		this.ultimologin = ultimologin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Entrada> getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Set<Entrada> entradas) {
		this.entradas = entradas;
	}

}
