package org.dinamizadores.dinaeventos.model;
// Generated 13-jun-2016 11:45:19 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "jbossforge")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8141392932334002184L;
	private int idusuario;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String telefono;
	private Date fechanac;
	private String direccion;
	private byte[] fotoperfil;
	private String password;
	private String cuentacorriente;
	private String iban;
	private Boolean bloqueado;
	private Boolean activo;
	private Date ultimologin;
	private Integer idsexo;
	private Integer idredessociales;
	private Integer idrol;
	private Integer idcodigopostal;

	public Usuario() {
	}

	public Usuario(int idusuario, String apellido1, String password) {
		this.idusuario = idusuario;
		this.apellido1 = apellido1;
		this.password = password;
	}
	public Usuario(int idusuario, String nombre, String apellido1,
			String apellido2, String email, String telefono, Date fechanac,
			String direccion, byte[] fotoperfil, String password,
			String cuentacorriente, String iban, Boolean bloqueado,
			Boolean activo, Date ultimologin, Integer idsexo,
			Integer idredessociales, Integer idrol, Integer idcodigopostal) {
		this.idusuario = idusuario;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
		this.fechanac = fechanac;
		this.direccion = direccion;
		this.fotoperfil = fotoperfil;
		this.password = password;
		this.cuentacorriente = cuentacorriente;
		this.iban = iban;
		this.bloqueado = bloqueado;
		this.activo = activo;
		this.ultimologin = ultimologin;
		this.idsexo = idsexo;
		this.idredessociales = idredessociales;
		this.idrol = idrol;
		this.idcodigopostal = idcodigopostal;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idusuario", unique = true, nullable = false)
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanac", length = 10)
	public Date getFechanac() {
		return this.fechanac;
	}

	public void setFechanac(Date fechanac) {
		this.fechanac = fechanac;
	}

	@Column(name = "direccion", length = 255)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Lob
	@Column(name = "fotoperfil")
	public byte[] getFotoperfil() {
		return this.fotoperfil;
	}

	public void setFotoperfil(byte[] fotoperfil) {
		this.fotoperfil = fotoperfil;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "cuentacorriente", length = 45)
	public String getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(String cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@Column(name = "iban", length = 45)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "bloqueado")
	public Boolean getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(Boolean bloqueado) {
		this.bloqueado = bloqueado;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimologin", length = 10)
	public Date getUltimologin() {
		return this.ultimologin;
	}

	public void setUltimologin(Date ultimologin) {
		this.ultimologin = ultimologin;
	}

	@Column(name = "idsexo")
	public Integer getIdsexo() {
		return this.idsexo;
	}

	public void setIdsexo(Integer idsexo) {
		this.idsexo = idsexo;
	}

	@Column(name = "idredessociales")
	public Integer getIdredessociales() {
		return this.idredessociales;
	}

	public void setIdredessociales(Integer idredessociales) {
		this.idredessociales = idredessociales;
	}

	@Column(name = "idrol")
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "idcodigopostal")
	public Integer getIdcodigopostal() {
		return this.idcodigopostal;
	}

	public void setIdcodigopostal(Integer idcodigopostal) {
		this.idcodigopostal = idcodigopostal;
	}

}
